import React from "react";

export function Footer() {
  return (
    <footer className="w-full border-t border-border bg-surface text-ink-muted text-xs">
      <div className="max-w-container mx-auto px-4 sm:px-6 py-8 space-y-4">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 text-xs text-ink-muted">
          <div>
            <span className="font-serif font-semibold text-sm text-ink block sm:inline mr-2">
              H2 Medical Report Simplifier
            </span>
            <span>A patient-facing tool for reading laboratory and clinical reports.</span>
          </div>
          <p className="text-xs text-ink-muted">
            [TEAM: confirm privacy statement]
          </p>
        </div>

        <div className="pt-3 border-t border-border text-xs text-ink-muted leading-relaxed">
          <p>
            <strong className="text-ink font-medium">Important clinical notice:</strong>{" "}
            Summaries are generated by artificial intelligence for educational understanding and may contain errors. H2 does not diagnose conditions, interpret symptoms, or replace the judgment of a licensed healthcare provider. Always review your laboratory findings directly with your physician.
          </p>
        </div>
      </div>
    </footer>
  );
}
