import { MedicalReport, MedicalTest, HistoricalValue } from "@/types/medical";

export const MOCK_HISTORICAL_GLUCOSE: HistoricalValue[] = [
  {
    date: "2026-01-14",
    month_label: "January",
    value: 91,
    reference_min: 70,
    reference_max: 99,
    unit: "mg/dL",
    report_id: "rep-004",
  },
  {
    date: "2026-04-12",
    month_label: "April",
    value: 94,
    reference_min: 70,
    reference_max: 99,
    unit: "mg/dL",
    report_id: "rep-003",
  },
  {
    date: "2026-07-20",
    month_label: "July",
    value: 98,
    reference_min: 70,
    reference_max: 99,
    unit: "mg/dL",
    report_id: "rep-002",
  },
  {
    date: "2026-09-18",
    month_label: "September",
    value: 109,
    reference_min: 70,
    reference_max: 99,
    unit: "mg/dL",
    report_id: "rep-001",
  },
];

export const MOCK_HISTORICAL_HEMOGLOBIN: HistoricalValue[] = [
  {
    date: "2026-01-14",
    month_label: "January",
    value: 14.4,
    reference_min: 13.8,
    reference_max: 17.2,
    unit: "g/dL",
    report_id: "rep-004",
  },
  {
    date: "2026-04-12",
    month_label: "April",
    value: 14.1,
    reference_min: 13.8,
    reference_max: 17.2,
    unit: "g/dL",
    report_id: "rep-003",
  },
  {
    date: "2026-07-20",
    month_label: "July",
    value: 14.3,
    reference_min: 13.8,
    reference_max: 17.2,
    unit: "g/dL",
    report_id: "rep-002",
  },
  {
    date: "2026-09-18",
    month_label: "September",
    value: 14.2,
    reference_min: 13.8,
    reference_max: 17.2,
    unit: "g/dL",
    report_id: "rep-001",
  },
];

export const MOCK_HISTORICAL_VITAMIN_D: HistoricalValue[] = [
  {
    date: "2026-01-14",
    month_label: "January",
    value: 36,
    reference_min: 30,
    reference_max: 100,
    unit: "ng/mL",
    report_id: "rep-004",
  },
  {
    date: "2026-04-12",
    month_label: "April",
    value: 32,
    reference_min: 30,
    reference_max: 100,
    unit: "ng/mL",
    report_id: "rep-003",
  },
  {
    date: "2026-07-20",
    month_label: "July",
    value: 27,
    reference_min: 30,
    reference_max: 100,
    unit: "ng/mL",
    report_id: "rep-002",
  },
  {
    date: "2026-09-18",
    month_label: "September",
    value: 22,
    reference_min: 30,
    reference_max: 100,
    unit: "ng/mL",
    report_id: "rep-001",
  },
];

export const MOCK_HISTORICAL_CHOLESTEROL: HistoricalValue[] = [
  {
    date: "2026-01-14",
    month_label: "January",
    value: 198,
    reference_min: 125,
    reference_max: 200,
    unit: "mg/dL",
    report_id: "rep-004",
  },
  {
    date: "2026-04-12",
    month_label: "April",
    value: 192,
    reference_min: 125,
    reference_max: 200,
    unit: "mg/dL",
    report_id: "rep-003",
  },
  {
    date: "2026-07-20",
    month_label: "July",
    value: 194,
    reference_min: 125,
    reference_max: 200,
    unit: "mg/dL",
    report_id: "rep-002",
  },
  {
    date: "2026-09-18",
    month_label: "September",
    value: 195,
    reference_min: 125,
    reference_max: 200,
    unit: "mg/dL",
    report_id: "rep-001",
  },
];

export const MOCK_HISTORICAL_PLATELETS: HistoricalValue[] = [
  {
    date: "2026-01-14",
    month_label: "January",
    value: 235,
    reference_min: 150,
    reference_max: 450,
    unit: "x10³/µL",
    report_id: "rep-004",
  },
  {
    date: "2026-04-12",
    month_label: "April",
    value: 248,
    reference_min: 150,
    reference_max: 450,
    unit: "x10³/µL",
    report_id: "rep-003",
  },
  {
    date: "2026-07-20",
    month_label: "July",
    value: 242,
    reference_min: 150,
    reference_max: 450,
    unit: "x10³/µL",
    report_id: "rep-002",
  },
  {
    date: "2026-09-18",
    month_label: "September",
    value: 240,
    reference_min: 150,
    reference_max: 450,
    unit: "x10³/µL",
    report_id: "rep-001",
  },
];

export const MOCK_TESTS_LATEST: MedicalTest[] = [
  {
    id: "test-001",
    test_name: "Fasting Glucose",
    slug: "fasting-glucose",
    value: 109,
    unit: "mg/dL",
    reference_range: "70 – 99 mg/dL",
    reference_min: 70,
    reference_max: 99,
    status: "above_range",
    trend: "increasing",
    previous_value: 98,
    change_absolute: 11,
    change_percentage: 11.2,
    anomaly: true,
    category: "Metabolic Panel",
    simple_explanation:
      "Measures sugar levels in the blood after an overnight fast. It indicates how efficiently your body manages glucose.",
    ml_analysis: {
      trend_direction: "increasing",
      anomaly_detected: true,
      confidence_score: 0.94,
      change_label: "+18 mg/dL over 4 reports",
      explanation:
        "Your reported values have shown an increasing trend across the available reports, moving from within range (91 mg/dL) to above the reference threshold (109 mg/dL).",
      historical_points_analyzed: 4,
    },
    historical_values: MOCK_HISTORICAL_GLUCOSE,
  },
  {
    id: "test-002",
    test_name: "Hemoglobin",
    slug: "hemoglobin",
    value: 14.2,
    unit: "g/dL",
    reference_range: "13.8 – 17.2 g/dL",
    reference_min: 13.8,
    reference_max: 17.2,
    status: "within_range",
    trend: "stable",
    previous_value: 14.3,
    change_absolute: -0.1,
    change_percentage: -0.7,
    anomaly: false,
    category: "Complete Blood Count",
    simple_explanation:
      "The protein in red blood cells that carries oxygen from your lungs to the rest of your body.",
    ml_analysis: {
      trend_direction: "stable",
      anomaly_detected: false,
      confidence_score: 0.98,
      change_label: "-0.2 g/dL overall",
      explanation:
        "Your hemoglobin values have remained stable across all recorded periods, staying consistently within the reference range.",
      historical_points_analyzed: 4,
    },
    historical_values: MOCK_HISTORICAL_HEMOGLOBIN,
  },
  {
    id: "test-003",
    test_name: "Vitamin D (25-Hydroxy)",
    slug: "vitamin-d",
    value: 22,
    unit: "ng/mL",
    reference_range: "30 – 100 ng/mL",
    reference_min: 30,
    reference_max: 100,
    status: "below_range",
    trend: "decreasing",
    previous_value: 27,
    change_absolute: -5,
    change_percentage: -18.5,
    anomaly: true,
    category: "Vitamins & Hormones",
    simple_explanation:
      "An essential vitamin for bone density and immune function, synthesized through sun exposure and diet.",
    ml_analysis: {
      trend_direction: "decreasing",
      anomaly_detected: true,
      confidence_score: 0.91,
      change_label: "-14 ng/mL over 4 reports",
      explanation:
        "A steady downward trend has been detected across the past three quarters, dropping below the lower reference boundary.",
      historical_points_analyzed: 4,
    },
    historical_values: MOCK_HISTORICAL_VITAMIN_D,
  },
  {
    id: "test-004",
    test_name: "Total Cholesterol",
    slug: "total-cholesterol",
    value: 195,
    unit: "mg/dL",
    reference_range: "125 – 200 mg/dL",
    reference_min: 125,
    reference_max: 200,
    status: "within_range",
    trend: "stable",
    previous_value: 194,
    change_absolute: 1,
    change_percentage: 0.5,
    anomaly: false,
    category: "Lipid Panel",
    simple_explanation:
      "An overall estimate of all the cholesterol types circulating in your bloodstream.",
    ml_analysis: {
      trend_direction: "stable",
      anomaly_detected: false,
      confidence_score: 0.96,
      change_label: "+1 mg/dL from prior report",
      explanation:
        "Total cholesterol has remained relatively flat and remains within the standard reference parameters.",
      historical_points_analyzed: 4,
    },
    historical_values: MOCK_HISTORICAL_CHOLESTEROL,
  },
  {
    id: "test-005",
    test_name: "Platelets",
    slug: "platelets",
    value: 240,
    unit: "x10³/µL",
    reference_range: "150 – 450 x10³/µL",
    reference_min: 150,
    reference_max: 450,
    status: "within_range",
    trend: "stable",
    previous_value: 242,
    change_absolute: -2,
    change_percentage: -0.8,
    anomaly: false,
    category: "Complete Blood Count",
    simple_explanation:
      "Blood cell fragments essential for normal blood clotting and tissue repair.",
    ml_analysis: {
      trend_direction: "stable",
      anomaly_detected: false,
      confidence_score: 0.99,
      change_label: "-2 x10³/µL change",
      explanation:
        "Platelet counts show high stability over time and align cleanly with typical reference bands.",
      historical_points_analyzed: 4,
    },
    historical_values: MOCK_HISTORICAL_PLATELETS,
  },
];

export const MOCK_REPORTS: MedicalReport[] = [
  {
    id: "rep-001",
    report_name: "Comprehensive Metabolic & Blood Panel",
    date: "2026-09-18",
    provider_or_lab: "Metro Health Diagnostic Center",
    tests_count: 5,
    status: "analyzed",
    tests: MOCK_TESTS_LATEST,
    summary: {
      total_tests: 5,
      within_range_count: 3,
      outside_range_count: 2,
      trends_detected_count: 2,
      anomalies_detected_count: 2,
      overview_text:
        "Analysis of your September 2026 report identified 3 test values within the expected reference range and 2 tests outside the range. Historical ML modeling flagged an upward trend in Fasting Glucose and a downward trend in Vitamin D across your last 4 recorded lab panels.",
      key_takeaways: [
        "Fasting Glucose has risen from 91 mg/dL in January to 109 mg/dL in September (+18 mg/dL overall).",
        "Vitamin D has decreased steadily from 36 ng/mL to 22 ng/mL over the same observation window.",
        "Hemoglobin, Total Cholesterol, and Platelet levels remain stable and within reference intervals.",
      ],
    },
  },
  {
    id: "rep-002",
    report_name: "Full Health Panel",
    date: "2026-07-20",
    provider_or_lab: "Metro Health Diagnostic Center",
    tests_count: 5,
    status: "analyzed",
    tests: [
      {
        ...MOCK_TESTS_LATEST[0],
        value: 98,
        status: "within_range",
        previous_value: 94,
        change_absolute: 4,
        anomaly: false,
      },
      {
        ...MOCK_TESTS_LATEST[1],
        value: 14.3,
        status: "within_range",
        previous_value: 14.1,
        change_absolute: 0.2,
      },
      {
        ...MOCK_TESTS_LATEST[2],
        value: 27,
        status: "below_range",
        previous_value: 32,
        change_absolute: -5,
        anomaly: false,
      },
      {
        ...MOCK_TESTS_LATEST[3],
        value: 194,
        status: "within_range",
        previous_value: 192,
        change_absolute: 2,
      },
      {
        ...MOCK_TESTS_LATEST[4],
        value: 242,
        status: "within_range",
        previous_value: 248,
        change_absolute: -6,
      },
    ],
    summary: {
      total_tests: 5,
      within_range_count: 4,
      outside_range_count: 1,
      trends_detected_count: 1,
      anomalies_detected_count: 0,
      overview_text:
        "July 2026 panel showed 4 out of 5 tests within expected bounds. Vitamin D first dropped slightly below target.",
      key_takeaways: [
        "Fasting Glucose was near upper threshold at 98 mg/dL.",
        "Vitamin D decreased to 27 ng/mL.",
        "All other hematologic markers remained normal.",
      ],
    },
  },
  {
    id: "rep-003",
    report_name: "Routine Blood Test",
    date: "2026-04-12",
    provider_or_lab: "Quest Diagnostics Lab",
    tests_count: 5,
    status: "analyzed",
    tests: [
      {
        ...MOCK_TESTS_LATEST[0],
        value: 94,
        status: "within_range",
        previous_value: 91,
        change_absolute: 3,
        anomaly: false,
      },
      {
        ...MOCK_TESTS_LATEST[1],
        value: 14.1,
        status: "within_range",
        previous_value: 14.4,
        change_absolute: -0.3,
      },
      {
        ...MOCK_TESTS_LATEST[2],
        value: 32,
        status: "within_range",
        previous_value: 36,
        change_absolute: -4,
      },
      {
        ...MOCK_TESTS_LATEST[3],
        value: 192,
        status: "within_range",
        previous_value: 198,
        change_absolute: -6,
      },
      {
        ...MOCK_TESTS_LATEST[4],
        value: 248,
        status: "within_range",
        previous_value: 235,
        change_absolute: 13,
      },
    ],
    summary: {
      total_tests: 5,
      within_range_count: 5,
      outside_range_count: 0,
      trends_detected_count: 0,
      anomalies_detected_count: 0,
      overview_text:
        "April 2026 routine follow-up with all 5 tracked laboratory values within reference ranges.",
      key_takeaways: [
        "All 5 parameters within standard ranges.",
        "Mild upward creep in glucose from 91 to 94 mg/dL.",
      ],
    },
  },
  {
    id: "rep-004",
    report_name: "Annual Health Checkup",
    date: "2026-01-14",
    provider_or_lab: "Primary Care Associates",
    tests_count: 5,
    status: "analyzed",
    tests: [
      {
        ...MOCK_TESTS_LATEST[0],
        value: 91,
        status: "within_range",
        previous_value: undefined,
        change_absolute: undefined,
        anomaly: false,
      },
      {
        ...MOCK_TESTS_LATEST[1],
        value: 14.4,
        status: "within_range",
        previous_value: undefined,
        change_absolute: undefined,
      },
      {
        ...MOCK_TESTS_LATEST[2],
        value: 36,
        status: "within_range",
        previous_value: undefined,
        change_absolute: undefined,
      },
      {
        ...MOCK_TESTS_LATEST[3],
        value: 198,
        status: "within_range",
        previous_value: undefined,
        change_absolute: undefined,
      },
      {
        ...MOCK_TESTS_LATEST[4],
        value: 235,
        status: "within_range",
        previous_value: undefined,
        change_absolute: undefined,
      },
    ],
    summary: {
      total_tests: 5,
      within_range_count: 5,
      outside_range_count: 0,
      trends_detected_count: 0,
      anomalies_detected_count: 0,
      overview_text:
        "Baseline annual panel establishing historical reference benchmarks.",
      key_takeaways: [
        "All parameters within optimal boundaries.",
        "Establishes baseline for subsequent quarterly tracking.",
      ],
    },
  },
];
